// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace guid_reactapp.Migrations
{
    [DbContext(typeof(TableContext))]
    [Migration("20180906122450_ResourceRequisitionCreate")]
    partial class ResourceRequisitionCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799");

            modelBuilder.Entity("CandidateModel.Models.Candidate", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Deadline");

                    b.Property<string>("Email");

                    b.Property<string>("File_Name");

                    b.Property<string>("Job_Requisition");

                    b.Property<int>("Stages");

                    b.HasKey("Id");

                    b.ToTable("Candidates");
                });

            modelBuilder.Entity("Models.Recruiter.ResourceRequisition", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("HiringManagerEmail");

                    b.Property<string>("Notes");

                    b.Property<DateTime>("PlannedDeadline");

                    b.Property<string>("Skills");

                    b.Property<int>("Stages");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("ResourceRequisitions");
                });

            modelBuilder.Entity("Models.SkillSets.SkillSet", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Node");

                    b.Property<string>("Parent");

                    b.HasKey("Id");

                    b.ToTable("SkillSets");
                });

            modelBuilder.Entity("QandAApi.Models.Item", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Ans");

                    b.Property<string>("Ques");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
